In [1]:
import numpy as np

In [2]:
## yukarıda yaptığımız şey önce numpy kütüphanesini import ettik sonrada onun ismini np diye kısalttık

In [3]:
list = [1,2,3,4,5,6,7,9,]

In [7]:
list_1 = np.array([(1,2,3) , (4,5,6), (7,8,9)])

In [8]:
list_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
## yukarıda numpy kütüphanesindeki hazır matris oluşturma fonksiyonunu kullandık

In [10]:
print(list_1.shape)

(3, 3)


In [13]:
## yukarıdaki komut boyutunu veriyor matriksin

In [12]:
print(list_1.size)

9


In [14]:
## yukarıdaki komut ise bize matriksin eleman sayısını veriyor

In [15]:
list_2 = np.arange(10)

In [16]:
list_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
list_2.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
## yukarıda yaptığımız şey ise önce list_2 denen bitane değişkene arange() komutu ile matriks oluşturduk sonra reshape() ilede boyutunu belirledik 

In [19]:
random_matris = np.random.randint(20,70,15)

In [20]:
random_matris

array([43, 40, 51, 61, 31, 56, 42, 56, 64, 22, 33, 51, 69, 67, 20])

In [21]:
## yukarıda yaptığımız şey ise random.randint(20,70,15) yaparak 20 ile 70 arasında 15 tane int olan sayıyı rasgele seçerek
## bi matriks oluşturdu 

In [22]:
print("Aritmetik ort.:\t", np.mean(random_matris) )
print("Medyan:\t", np.median(random_matris) )
print("Varyans:\t", np.var(random_matris) )
print("Standart Sapma:\t", np.std(random_matris) )


Aritmetik ort.:	 47.06666666666667
Medyan:	 51.0
Varyans:	 230.59555555555553
Standart Sapma:	 15.185373079235015


In [23]:
## yukarıda numpy kütüphanesi sayessinde verilen özel tanımlı fonksiyonlar ile bu işlemleri yaptık heyoooo